#!/usr/bin/env bash
# sandbox_setup.sh — stand up an isolated sandbox instance of the target for Stage 5 pen-testing.
#
# This script is a STARTING POINT. Customize per-project. Stage 5 must always confirm:
#   * bindings on 127.0.0.1 or private networks only
#   * ephemeral / seeded data (never a production dump)
#   * clean teardown on exit
#
# Usage: sandbox_setup.sh <target_dir> [--mode docker|compose|venv|process|none]

set -euo pipefail

TARGET_DIR=""
MODE="compose"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode) MODE="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 <target_dir> [--mode docker|compose|venv|process|none]" >&2
      exit 2 ;;
    *) TARGET_DIR="$1"; shift ;;
  esac
done

if [[ -z "${TARGET_DIR}" ]]; then
  echo "error: target_dir required" >&2
  exit 2
fi

SANDBOX_DIR="${TARGET_DIR%/}/.security-audit/sandbox"
mkdir -p "${SANDBOX_DIR}"

case "${MODE}" in
  compose)
    if [[ ! -f "${TARGET_DIR%/}/docker-compose.yml" && ! -f "${TARGET_DIR%/}/compose.yml" ]]; then
      echo "error: no docker-compose.yml / compose.yml in ${TARGET_DIR}" >&2
      exit 1
    fi
    SRC_COMPOSE="${TARGET_DIR%/}/docker-compose.yml"
    [[ -f "${TARGET_DIR%/}/compose.yml" ]] && SRC_COMPOSE="${TARGET_DIR%/}/compose.yml"

    # Copy compose file; an override is produced that binds ports to 127.0.0.1 only.
    cp "${SRC_COMPOSE}" "${SANDBOX_DIR}/docker-compose.yml"
    cat > "${SANDBOX_DIR}/docker-compose.override.yml" <<'YAML'
# Auto-generated by security-audit. Review before use.
# Goal: constrain published ports to loopback only.
services: {}
YAML
    echo "Compose sandbox scaffold at ${SANDBOX_DIR}"
    echo "Next: edit the override to bind each published port to 127.0.0.1 only, then:"
    echo "  docker compose -f ${SANDBOX_DIR}/docker-compose.yml \\"
    echo "                -f ${SANDBOX_DIR}/docker-compose.override.yml up -d"
    ;;
  docker)
    echo "Build and run with: docker build -t sec-sandbox:latest ${TARGET_DIR} && \\"
    echo "docker run --rm -p 127.0.0.1:<port>:<port> --network none sec-sandbox:latest"
    ;;
  venv)
    echo "Create a venv / virtualenv isolated to this sandbox and bind the app to 127.0.0.1."
    echo "  python3 -m venv ${SANDBOX_DIR}/venv && source ${SANDBOX_DIR}/venv/bin/activate"
    echo "  pip install -r ${TARGET_DIR}/requirements.txt"
    ;;
  process)
    echo "Start the app in an isolated subshell bound to 127.0.0.1 only."
    echo "Record PID to ${SANDBOX_DIR}/app.pid so teardown.sh can stop it."
    ;;
  none)
    echo "No sandbox selected. Stage 5 will be static-only for this target."
    echo "Record the gap in coverage_gaps.md."
    ;;
  *)
    echo "error: unknown mode ${MODE}" >&2
    exit 2 ;;
esac
